---
title: "clean_aqi_data"
author: "Christine Guo"
output: html_document
---

```{r Setup, include=FALSE, results='hide', warning=FALSE}
knitr::opts_chunk$set(echo = T, cache = T, fig.width=8, fig.height=4,
                      warning = F)
options(scipen = 0, digits = 3)  ## controls base R output

## Package setup
if(!require("pacman")) install.packages("pacman")

pacman::p_load(tidyverse, dplyr)
```


```{r}
# read in data
aqi_data <- read.csv("data/annual_aqi_by_county_2019.csv")
# remove US territories from data
aqi_data <- filter(aqi_data, State != "Virgin Islands" & State != "Puerto Rico" & State != "Country Of Mexico")
# add county/borough/parish to county names 
for(i in seq_along(aqi_data$County)) {
  if(aqi_data$State[i] == "Louisiana") {
    aqi_data$County[i] <- paste(aqi_data$County[i], "Parish")
  }
  else if(aqi_data$State[i] == "Alaska") {
    aqi_data$County[i] <- paste(aqi_data$County[i], "Borough")
  }
  else if(!grepl("City", aqi_data$County[i], fixed=TRUE) && !grepl("District of Columbia", aqi_data$County[i], fixed=TRUE)){
    aqi_data$County[i] <- paste(aqi_data$County[i], "County")
  }
}
# remove the year column
aqi_data <- aqi_data[ , -which(names(aqi_data) %in% c("Year"))]

# change state column to state abreviations
for(i in seq_along(aqi_data$State)) {
  if(!grepl("District of Columbia", aqi_data$County[i], fixed=TRUE)) {
    aqi_data$State[i] <- state.abb[grep(aqi_data$State[i], state.name)]
  }
}
# write data to a new file 
write.csv(aqi_data, "data/cleaned_annual_aqi_by_county_2019.csv")
```

